//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtPayment
    {
        public DebtPayment()
        {
            this.DebtMonthlyPayments = new HashSet<DebtMonthlyPayment>();
        }
    
        public int Code { get; set; }
        public Nullable<int> MembersCode { get; set; }
        public Nullable<int> DebtKindCode { get; set; }
        public string PaymentDate { get; set; }
        public string paymentTime { get; set; }
        public Nullable<double> StockAvg { get; set; }
        public Nullable<double> DebtCash { get; set; }
        public Nullable<double> DebtPay { get; set; }
        public Nullable<double> DebtWage { get; set; }
        public Nullable<byte> countt { get; set; }
        public Nullable<double> PaymentCash { get; set; }
        public string CashFirstDate { get; set; }
        public string CashEndDate { get; set; }
        public Nullable<double> LatenPenalty { get; set; }
        public Nullable<byte> Status { get; set; }
        public string PayOffDate { get; set; }
        public string PayOffTime { get; set; }
        public string Comment { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<int> ChequeNumber { get; set; }
        public Nullable<byte> DebtWageKind { get; set; }
    
        public virtual DebtKInd DebtKInd { get; set; }
        public virtual Member Member { get; set; }
        public virtual ICollection<DebtMonthlyPayment> DebtMonthlyPayments { get; set; }
    }
}
