//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtKInd
    {
        public DebtKInd()
        {
            this.DebtPayments = new HashSet<DebtPayment>();
        }
    
        public int Code { get; set; }
        public string Descriptions { get; set; }
        public Nullable<byte> count { get; set; }
        public Nullable<double> DebtCash { get; set; }
        public Nullable<double> WageCash { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<int> Year { get; set; }
        public string Fromdate { get; set; }
        public string ToDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<byte> ReciveWageKind { get; set; }
    
        public virtual ICollection<DebtPayment> DebtPayments { get; set; }
    }
}
