//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtPrint
    {
        public int code { get; set; }
        public Nullable<int> Debtcode { get; set; }
        public Nullable<byte> Debtnumber { get; set; }
        public Nullable<long> cash1 { get; set; }
        public Nullable<int> debt1 { get; set; }
        public Nullable<long> cash2 { get; set; }
    }
}
