//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtMonthlyPayment
    {
        public int Code { get; set; }
        public Nullable<int> MembersCode { get; set; }
        public Nullable<int> DebtCode { get; set; }
        public string DebtDate { get; set; }
        public string DebtDateReal { get; set; }
        public Nullable<byte> DebtNumber { get; set; }
        public Nullable<double> DebtCash { get; set; }
        public Nullable<double> PenaltyCash { get; set; }
        public Nullable<double> TotalCash { get; set; }
        public Nullable<double> PayoffCash { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Comment { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> DelayDate { get; set; }
    
        public virtual DebtPayment DebtPayment { get; set; }
        public virtual Member Member { get; set; }
    }
}
