//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtCreditKind
    {
        public DebtCreditKind()
        {
            this.DebtCreditAccs = new HashSet<DebtCreditAcc>();
        }
    
        public byte Code { get; set; }
        public string Description { get; set; }
        public Nullable<byte> Kind { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual ICollection<DebtCreditAcc> DebtCreditAccs { get; set; }
    }
}
