//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class familial_bankEntities : DbContext
    {
        public familial_bankEntities()
            : base("name=familial_bankEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAcc> BankAccs { get; set; }
        public virtual DbSet<DebtKInd> DebtKInds { get; set; }
        public virtual DbSet<DebtMonthTemp> DebtMonthTemps { get; set; }
        public virtual DbSet<EventsDescription> EventsDescriptions { get; set; }
        public virtual DbSet<EventsLog> EventsLogs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<MemberShipRight> MemberShipRights { get; set; }
        public virtual DbSet<MonthPayment> MonthPayments { get; set; }
        public virtual DbSet<PaymentMonthTemp> PaymentMonthTemps { get; set; }
        public virtual DbSet<RequestCheck> RequestChecks { get; set; }
        public virtual DbSet<SignaturesAcc> SignaturesAccs { get; set; }
        public virtual DbSet<TblUser> TblUsers { get; set; }
        public virtual DbSet<PaymentMember> PaymentMembers { get; set; }
        public virtual DbSet<DebtPayment> DebtPayments { get; set; }
        public virtual DbSet<DebtCreditAcc> DebtCreditAccs { get; set; }
        public virtual DbSet<DebtCreditKind> DebtCreditKinds { get; set; }
        public virtual DbSet<DebtMonthlyPayment> DebtMonthlyPayments { get; set; }
        public virtual DbSet<DebtPrint> DebtPrints { get; set; }
    
        public virtual int DebtInsertprint(Nullable<int> debtCash, Nullable<int> debtpayment, Nullable<int> debtcount, Nullable<int> debtcode)
        {
            var debtCashParameter = debtCash.HasValue ?
                new ObjectParameter("DebtCash", debtCash) :
                new ObjectParameter("DebtCash", typeof(int));
    
            var debtpaymentParameter = debtpayment.HasValue ?
                new ObjectParameter("debtpayment", debtpayment) :
                new ObjectParameter("debtpayment", typeof(int));
    
            var debtcountParameter = debtcount.HasValue ?
                new ObjectParameter("debtcount", debtcount) :
                new ObjectParameter("debtcount", typeof(int));
    
            var debtcodeParameter = debtcode.HasValue ?
                new ObjectParameter("debtcode", debtcode) :
                new ObjectParameter("debtcode", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DebtInsertprint", debtCashParameter, debtpaymentParameter, debtcountParameter, debtcodeParameter);
        }
    }
}
