//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.SignaturesAccs = new HashSet<SignaturesAcc>();
            this.PaymentMembers = new HashSet<PaymentMember>();
            this.DebtPayments = new HashSet<DebtPayment>();
            this.DebtMonthlyPayments = new HashSet<DebtMonthlyPayment>();
        }
    
        public int Code { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string NationalCode { get; set; }
        public string BirthDate { get; set; }
        public string IdentityNumber { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<byte> Relation { get; set; }
        public Nullable<bool> Status { get; set; }
        public string MembershipDate { get; set; }
        public string MembershipTime { get; set; }
        public string MembershipDateCancel { get; set; }
        public Nullable<int> MainMemberShip { get; set; }
        public Nullable<int> userCode { get; set; }
        public string ipadress { get; set; }
        public Nullable<bool> deleted { get; set; }
    
        public virtual ICollection<SignaturesAcc> SignaturesAccs { get; set; }
        public virtual ICollection<PaymentMember> PaymentMembers { get; set; }
        public virtual ICollection<DebtPayment> DebtPayments { get; set; }
        public virtual ICollection<DebtMonthlyPayment> DebtMonthlyPayments { get; set; }
    }
}
