//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberShipRight
    {
        public byte Code { get; set; }
        public string Description { get; set; }
        public Nullable<double> Cashfixed { get; set; }
        public Nullable<int> Year { get; set; }
        public string FromDate { get; set; }
        public string Todate { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
