//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMember
    {
        public int Code { get; set; }
        public Nullable<int> MembersCode { get; set; }
        public string PaymentDate { get; set; }
        public string PaymentTime { get; set; }
        public Nullable<double> Cash { get; set; }
        public Nullable<byte> kind { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<byte> Month { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> SerialNo { get; set; }
        public string Comment { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
