//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMonthTemp
    {
        public int Code { get; set; }
        public Nullable<int> MembershipCode { get; set; }
        public Nullable<int> Year { get; set; }
        public byte Month { get; set; }
        public Nullable<double> CashDefault { get; set; }
        public Nullable<double> CashPayment { get; set; }
        public string Datetemp { get; set; }
        public Nullable<System.TimeSpan> TimeTemp { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
