//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestCheck
    {
        public byte Code { get; set; }
        public Nullable<byte> AccCode { get; set; }
        public Nullable<int> CheckNumberFrom { get; set; }
        public Nullable<int> CheckNumberTo { get; set; }
        public Nullable<byte> countt { get; set; }
        public Nullable<int> Usercode { get; set; }
        public string IpAdress { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> transferee_user { get; set; }
        public string Delivery_date { get; set; }
    
        public virtual BankAcc BankAcc { get; set; }
    }
}
