//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace familial_bank
{
    using System;
    using System.Collections.Generic;
    
    public partial class SignaturesAcc
    {
        public byte Code { get; set; }
        public Nullable<int> MembersCode { get; set; }
        public Nullable<byte> AccCode { get; set; }
        public Nullable<bool> Status { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<int> UserCode { get; set; }
        public string IpAdress { get; set; }
    
        public virtual BankAcc BankAcc { get; set; }
        public virtual Member Member { get; set; }
    }
}
